config/routes.rb
Rails.application.routes.draw do
  resources :events
  get 'calendar/show'

  get 'uploads/new'
  get 'uploads/create'
  get 'uploads/index'
  get 'dashboards/join'
  put 'dashboards/join'
  post 'dashboards/search'

  resources :uploads
  resources :news_feeds

  resources :dashboards, shallow: true do
    resources :uploads
    resources :news_feeds
  end

  devise_for :users
  resource :users
  resource :calendar, only: [:show], controller: :calendar
  root 'user#home'

  get "/wyncode" => redirect("http://wyncode.co/")
  get "/about" => 'user#about'


end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  has_many :invites
  has_many :users, through: :invites
  has_many :uploads, dependent: :destroy
  has_many :news_feeds, dependent: :destroy

  validates :user_id, presence: true
  validates :token, uniqueness: true


  def self.search(search)
    where("token LIKE ?", "%#{search}%")
  end

  def set_user(user)
    self.user_id = user.id
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :set_dashboard, only: [:show, :edit, :update, :destroy]
  before_action :set_dashboards, only: [:join]
  before_action :authenticate_user!
  before_action :generate_token, only: [:create]
  # GET /dashboards
  # GET /dashboards.json
  def index
    @dashboards = Dashboard.all
  end

  def search
    @dashboard = Dashboard.find_by(token: params[:search])
    @news_feed = NewsFeed.new
    render 'show'
  end


  # GET /dashboards/1
  # GET /dashboards/1.json
  def show
    @news_feed = NewsFeed.new
    @upload = Upload.new
    @news_feeds = NewsFeed.all
    @uploads = Upload.all
  end

  # GET /dashboards/new
  def new
    @dashboard = Dashboard.new
  end

  # GET /dashboards/1/edit
  def edit
  end

  # POST /dashboards
  # POST /dashboards.json
  def create
    # render plain: params.to_json
    @dashboard = Dashboard.new(dashboard_params)
    @dashboard.set_user(current_user)
    @dashboard.token = @token

    respond_to do |format|
      if @dashboard.save
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully created.' }
        format.json { render :show, status: :created, location: @dashboard }
      else
        format.html { render :new }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboards/1
  # PATCH/PUT /dashboards/1.json
  def update
    respond_to do |format|
      if @dashboard.update(dashboard_params)
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @dashboard }
      else
        format.html { render :edit }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1
  # DELETE /dashboards/1.json
  def destroy
    @dashboard.destroy
    respond_to do |format|
      format.html { redirect_to dashboards_url, notice: 'Dashboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard
        @dashboard = Dashboard.find(params[:id])
    end

    def generate_token
      @token = SecureRandom.uuid
    end

    def set_dashboards
      @dashboards = Dashboard.all
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def dashboard_params
      params.require(:dashboard).permit(:title, :token, :user_id, :dashboard_id)
    end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_form.html.erb
<%= form_for(@dashboard) do |f| %>
  <% if @dashboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dashboard.errors.count, "error") %> prohibited this dashboard from being saved:</h2>

      <ul>
      <% @dashboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboards/edit.html.erb
<h1>Editing Dashboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @dashboard %> |
<%= link_to 'Back', dashboards_path %>

app/views/dashboards/index.html.erb
<% @user = current_user %>
<div id=entire_dashboard_index>
<div id="title">
  <h1>Hello <%= @user.name %>!</h1>
</div>

<div id="dashboard_list">
  <h2>Your Dashboards</h2>
    <% @dashboards.each do |dashboard| %>

    <% if @user.id == dashboard.user_id %>
        <div class="each_dashboard">
            <%= dashboard.title %>
            <%= link_to 'Show', dashboard, class:"dashboard_links" %>
            <%= link_to 'Edit', edit_dashboard_path(dashboard), class:"dashboard_links" %>
            <%= link_to 'Destroy', dashboard, method: :delete, data: { confirm: 'Are you sure?' }, class:"dashboard_links" %></p>
        </div>
        <br>
        <% else %>
      <% end %>
  <% end %>
</div>

<div id="dashboard_join">
  <h3>Join a Dashboard</h3>
  <%= form_tag(dashboards_search_path, id: "search-form") do %>
    <%= text_field_tag :search, params[:g], placeholder: "Enter Dashboard Code" %>
    <%= submit_tag "Search" %>
  <% end %>
</div>

<div id="dashbord_links">
<p class="new_dashboard"><%= link_to 'New Dashboard', new_dashboard_path %></p>
<p class="new_dashboard"><%= link_to 'Join Dashboard', dashboards_join_path %></p>
</div>
</div>

app/views/dashboards/join.html.erb
<h1>Join Dashboard</h1>

app/views/dashboards/new.html.erb
<h1>New Dashboard</h1>

<%= render 'form' %>

<%= link_to 'Back', dashboards_path %>

app/views/dashboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @dashboard.title %>
</p>

<!-- XXXXXXXXXX - Calendar Section XXXXXXXXXXXXX -->
<div id="main">
  <article>
    <p>Calendar view.</p>
    <%= link_to "Calendar", calendar_path %>
  </article>
<!-- XXXXXXXXXX - News Feed Dashboard Section XXXXXXXXXXXXX -->
  <aside>
    <h3>Listing News Feeds</h3>

    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Body</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @dashboard.news_feeds.each do |news_feed| %>
          <tr>
            <td><%= news_feed.title %></td>
            <td><%= news_feed.body %></td>
            <td><%= link_to 'Show', news_feed %></td>
            <td><%= link_to 'Edit', edit_news_feed_path(news_feed) %></td>
            <td><%= link_to 'Destroy', news_feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <!-- Subsection - News Feed Dashboard Subs -->
    <div ="news_feed" class>
      <%= link_to 'New Event', new_dashboard_news_feed_path(@dashboard.id) %>
    </aside>

  </div>

  <div id="dashboard_bottom_row">
          <div class="chat">
            <p>This is the chat feature</p>
          </div>

          <div class="docs">
            <%= image_tag ("document-square.png") %>
            <p>Documents</p>
            <%= link_to 'New Document', uploads_new_path %>
        </div>
  </div>

<!-- New News Feed Form -->

  <!-- <h3>Add a news item!</h3>
  <%= form_for [@dashboard, @news_feed] do |f| %>
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div> -->

<!-- Uploads Shit Below HERE -->

<!-- <div class="uploads_list">
  <div class="row">
    <% @dashboard.uploads.each do |upload| %>
      <div class="col-md-4 portfolio-item">
        <%= image_tag ("document.png") %>
        <h3 class ="index_center"><%= link_to upload.name, upload.url%></h3>
      </div>
    <% end %>
  </div>
</div>

<hr>

<div class ="upload">
  <p>This space is reserved for linking to uploads.</p>
  <%= form_for @dashboard.uploads.new do |f| %>
    <%= f.file_field :file  %>
    <%= f.submit 'Upload file' %>
  <% end %>
</div> -->



  <%= link_to 'Edit', edit_dashboard_path(@dashboard) %>
  | <%= link_to 'Back', dashboards_path %>