config/routes.rb
Rails.application.routes.draw do
  resources :events
  get 'calendar/show'

  get 'uploads/new'
  get 'uploads/create'
  get 'uploads/index'
  get 'dashboards/join'
  put 'dashboards/join'
  post 'dashboards/search'

  resources :uploads
  resources :news_feeds

  resources :dashboards, shallow: true do
    resources :uploads
    resources :news_feeds
  end

  devise_for :users
  resource :users
  resource :calendar, only: [:show], controller: :calendar
  root 'user#home'

  get "/wyncode" => redirect("http://wyncode.co/")
  get "/about" => 'user#about'


end

app/models/news_feed.rb
class NewsFeed < ActiveRecord::Base
  belongs_to :dashboard
  validates :dashboard_id, presence: true


end

app/controllers/news_feeds_controller.rb
class NewsFeedsController < ApplicationController
  before_action :set_news_feed, only: [:show, :edit, :update, :destroy]
  before_action :set_dashboard, only: [:create, :new, :index]
  before_action :authenticate_user!


  # GET /news_feeds
  # GET /news_feeds.json
  def index
    @news_feeds = @dashboard.news_feeds
  end

  # GET /news_feeds/1
  # GET /news_feeds/1.json
  def show
  end

  # GET /news_feeds/new
  def new
    @news_feed = @dashboard.news_feeds.new
  end

  # GET /news_feeds/1/edit
  def edit
  end

  # POST /news_feeds
  # POST /news_feeds.json
  def create
    # render plain: params.to_json

    @news_feed = @dashboard.news_feeds.new(news_feed_params)

    respond_to do |format|
      if @news_feed.save
        format.html { redirect_to @news_feed, notice: 'Newsfeed was successfully created.' }
        format.json { render :show, status: :created, location: @news_feed }
      else
        format.html { render :new }
        format.json { render json: @news_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_feeds/1
  # PATCH/PUT /news_feeds/1.json
  def update
    respond_to do |format|
      if @news_feed.update(news_feed_params)
        format.html { redirect_to @news_feed, notice: 'News feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @news_feed }
      else
        format.html { render :edit }
        format.json { render json: @news_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_feeds/1
  # DELETE /news_feeds/1.json
  def destroy
    @news_feed.destroy
    respond_to do |format|
      format.html { redirect_to news_feeds_url, notice: 'News feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_news_feed
        @news_feed = NewsFeed.find(params[:id])
    end

    def set_dashboard
        @dashboard = Dashboard.find params[:dashboard_id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_feed_params
      params.require(:news_feed).permit(:title, :body, :dashboard_id)
    end

end

app/helpers/news_feeds_helper.rb
module NewsFeedsHelper
end

app/views/news_feeds/_form.html.erb
<%= form_for(@news_feed) do |f| %>
  <% if @news_feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news_feed.errors.count, "error") %> prohibited this news_feed from being saved:</h2>

      <ul>
      <% @news_feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>





  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news_feeds/edit.html.erb
<h1>Editing News Feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @news_feed %> |
<%= link_to 'Back', news_feeds_path %>

app/views/news_feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing News Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Dashboard</th>
      <th>Dashboard</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news_feeds.each do |news_feed| %>
      <tr>
        <td><%= news_feed.title %></td>
        <td><%= news_feed.body %></td>
        <td><%= news_feed.dashboard_id %></td>
        <td><%= news_feed.dashboard %></td>
        <td><%= link_to 'Show', news_feed %></td>
          <td><%= link_to 'Edit', edit_news_feed_path(news_feed) %></td>
          <td><%= link_to 'Destroy', news_feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News feed', new_news_feed_path %>

<%= link_to 'Dashboard', dashboards_path %>

app/views/news_feeds/new.html.erb
<h1>New News Feed</h1>

<%= render 'form' %>

app/views/news_feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news_feed.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @news_feed.body %>
</p>

<p>
  <strong>Dashboard:</strong>
  <%= @news_feed.dashboard_id %>
</p>

<p>
  <strong>Dashboard:</strong>
  <%= @news_feed.dashboard %>
</p>

<%= link_to 'Edit', edit_news_feed_path(@news_feed) %> |
<%= link_to 'Back', dashboard_path(@news_feed.dashboard) %>